---
all:
  hosts:
    sonar-01:
      ansible_host: 51.250.68.108
    nexus-01:
      ansible_host: 51.250.66.68
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: momukeev
    ansible_user: mairambek